### ISSUE TITLE
Please Add Meaningful String Differences

### ISSUE THREAD

**Issue by jdscolam** [justsml/json-diff-performance#1]
This is a great start to a benchmark!  Probably more accurate than what I'm doing, though I'd be happy to share.  That being said, it would be good to have some meaningful text differences (e.g. text sizes over 60 chars, maybe even several paragraphs long) to really stretch the performance.  I know that this will likely test the performance of the underlying string diff implementation (likely google-diff-match-patch in most cases), but it adds a more accurate measure of performance.

I'd be interesting to see what happens, but my gut tells me there will be a severe drop-off in performance across all the libraries.  What do you think?

**Comment by justsml** [comment]
Hey @jdscolam - thanks for the feedback.
I've updated the project, please let me know what you think.

### Example results:

![image](https://cloud.githubusercontent.com/assets/397632/14098912/d7ebbcec-f53d-11e5-957a-d4a02c6f86c7.png)

![image](https://cloud.githubusercontent.com/assets/397632/14099089/9399c0b4-f53f-11e5-9d48-d89447742205.png)
