### ISSUE TITLE
A quick way to chat

### ISSUE THREAD

**Issue by jdscolam** [justsml/json-diff-performance#5]
@justsml is there a quick way to chat in the next few days, like Google Hangouts or something?  I'm seeing some serious differences between your results and my results on the string diff.  I don't think I've ever gotten performance numbers as good as you're posting, and I'd like to compare our approaches.

**Comment by justsml** [comment]
Hey @jdscolam definitely - send me an email or just hangouts me direct at `dan /at/ danlevy.net`
Please post your results, I'd love to have more #'s to compare.

**Comment by justsml** [comment]
I should also mention the test was run on a PC w/ 32GB RAM & a new i7 CPU OC'd to ~4Ghz... So that might skew things a bit. :smile:

**Comment by justsml** [comment]
Here's results from my MacBook Pro:
![image](https://cloud.githubusercontent.com/assets/397632/14156163/34860800-f682-11e5-9aad-df88484f7c49.png)
